language: csharp
solution: ConsoleApp1.sln 
install:
  - nuget restore ConsoleApp1.sln 
 script:
  - xbuild /p:Configuration=Release ConsoleApp1.sln
  - mono ./NUnit.Runners.3.9.0/tools/nunit-console.exe ./ConsoleApp1Test/bin/Release/ConsoleApp1Test.dll